name: arsip_berita_app
description: Arsip Berita App (Flutter + Supabase, offline-first)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  http: ^1.2.1
  html: ^0.15.4
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  share_plus: ^9.0.0
  file_saver: ^0.2.9+1
  palette_generator: ^0.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/theme/app.png
