name: arsip_berita_app
description: Arsip Berita App (Flutter + Supabase, offline-first)
publish_to: 'none'
# Bump version for new release
# Format: version: [major.minor.patch]+[build_number]
version: 1.8.0+20

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  http: ^1.2.1
  html: ^0.15.4
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  share_plus: ^12.0.0
  file_saver: ^0.2.9+1
  palette_generator: ^0.3.3
  shared_preferences: ^2.2.2
  file_picker: ^8.0.6
  flutter_widget_from_html_core: ^0.16.1
  google_sign_in: ^6.2.1
  googleapis: ^13.0.0
  archive: ^3.4.11
  flutter_quill: ^11.4.2
  url_launcher: ^6.3.1

  flutter_localizations:
    sdk: flutter
  flutter_quill_delta_from_html: ^1.5.3
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/theme/app.png
    - assets/theme/arsip_berita_app.png

# Launcher icons config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/theme/arsip_berita_app.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/theme/arsip_berita_app.png
  min_sdk_android: 21


