import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';
import '../services/ai_summarizer_service.dart';
import '../services/rss_news_service.dart';
import '../ui/design.dart';

class AskAICommandDialog extends StatefulWidget {
  final QuillController controller;

  const AskAICommandDialog({
    super.key,
    required this.controller,
  });

  @override
  State<AskAICommandDialog> createState() => _AskAICommandDialogState();
}

class _AskAICommandDialogState extends State<AskAICommandDialog> {
  final TextEditingController _commandController = TextEditingController();
  bool _isLoading = false;
  final AISummarizerService _aiService = AISummarizerService();
  final RSSNewsService _rssService = RSSNewsService();

  bool _containsNewsKeywords(String command) {
    final newsKeywords = [
      // Explicit category triggers
      'berita politik', 'berita ekonomi', 'berita olahraga', 'berita teknologi',
      'berita kesehatan', 'berita pendidikan', 'berita hukum', 'berita internasional',

      // General news terms
      'berita', 'news', 'hari ini', 'terkini', 'terbaru', 'breaking', 'headline',

      // Specific categories (single words)
      'politik', 'pemerintah', 'presiden', 'dpr', 'kpu', 'partai',
      'ekonomi', 'bisnis', 'investasi', 'saham', 'inflasi', 'bank',
      'olahraga', 'bola', 'timnas', 'liga', 'pertandingan',
      'teknologi', 'gadget', 'startup', 'digital', 'internet',
      'kesehatan', 'obat', 'dokter', 'rumah sakit', 'virus',
      'pendidikan', 'sekolah', 'universitas', 'siswa', 'kuliah',
      'hukum', 'pengadilan', 'kasus', 'polisi', 'korupsi',
      'internasional', 'luar negeri', 'global', 'asean',

      // Media terms
      'media', 'wartawan', 'jurnalistik', 'koran', 'majalah', 'topik'
    ];

    final lowerCommand = command.toLowerCase();
    return newsKeywords.any((keyword) => lowerCommand.contains(keyword));
  }

  @override
  void dispose() {
    _commandController.dispose();
    super.dispose();
  }

  void _insertToEditor(String content) {
    final insertIndex = widget.controller.selection.baseOffset;

    // Add formatted header and content
    final summaryWithHeader = '🤖 [Generated by AI]\n$content\n\n';

    widget.controller.document.insert(insertIndex, summaryWithHeader);
    widget.controller.document.insert(insertIndex + summaryWithHeader.length, '\n\n');

    // URLs are preserved as plain text and remain visible
    // Users can copy-paste them to browser for clickable access
  }

  Future<void> _executeCommand() async {
    if (_commandController.text.trim().isEmpty) return;

    setState(() {
      _isLoading = true;
    });

    try {
      // Prepare command with context
      final command = _commandController.text.trim();

      // Check if command requires real-time news data
      final needsWebSearch = _containsNewsKeywords(command);

      String rssResult = '';
      if (needsWebSearch) {
        setState(() {
          _isLoading = true;
        });
        rssResult = await _rssService.searchNews(command);
        print('🔍 RSS Result length: ${rssResult.length}');
        print('🔗 URL check: ${rssResult.contains('http') ? 'URLs found' : 'No URLs found'}');
      }

      final contextualCommand = '''
Anda adalah asisten AI untuk arsip berita dengan akses RSS feeds dari media Indonesia.

${needsWebSearch ? '''
📰 **HASIL RSS BERITA TERKINI:**
$rssResult

PENTING: Analisis hasil RSS di atas dan berikan ringkasan yang terstruktur untuk arsip berita.

**WAJIB:**
1. Pertahankan SEMUA link berita yang ada di hasil RSS
2. Format ulang hasil dengan tetap menyertakan semua link URL lengkap
3. Tidak menghapus atau mengubah link berita manapun
4. Link berita harus tetap terlihat jelas dalam format: 🔗 Link Berita: [URL LENGKAP]
5. Jangan memfilter atau menghilangkan informasi link
''' : '''
Anda memiliki akses ke template dan format arsip berita. Berikan respons yang sesuai dengan konteks arsip berita.
'''}

Perintah asli: $command

Berikan jawaban yang:
- Terstruktur dengan jelas untuk format arsip berita
- Format yang mudah dibaca
- Jika ada RSS results, WAJIB pertahankan semua link berita
- Jangan menghapus atau memodifikasi link berita
- Link berita harus tetap terlihat dengan format: 🔗 Link Berita: [URL LENGKAP]
- Relevan dengan kebutuhan konten arsip berita
''';

      final result = await _aiService.summarizeText(
        rssResult.isEmpty ? contextualCommand : '$rssResult\n\n$contextualCommand',
        customPrompt: contextualCommand,
      );

      if (mounted) {
        Navigator.of(context).pop();
        _insertToEditor(result);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${e.toString()}'),
            backgroundColor: DS.danger,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Row(
        children: [
          Icon(Icons.auto_awesome, color: DS.accent),
          const SizedBox(width: 8),
          const Text('Ask AI Command'),
        ],
      ),
      content: SizedBox(
        width: MediaQuery.of(context).size.width * 0.8,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'AI dengan RSS feeds gratis - berita terkini dari media Indonesia',
              style: TextStyle(
                fontSize: 14,
                color: DS.textDim,
              ),
            ),
            const SizedBox(height: 16),

            // Command input field
            TextField(
              controller: _commandController,
              decoration: InputDecoration(
                hintText: 'Contoh: Berita politik terkini, Analisis ekonomi Indonesia, Olahraga hari ini, Template berita...',
                border: const OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(8)),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: const BorderRadius.all(Radius.circular(8)),
                  borderSide: BorderSide(color: DS.border),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: const BorderRadius.all(Radius.circular(8)),
                  borderSide: BorderSide(color: DS.accent),
                ),
                filled: true,
                fillColor: DS.surface,
              ),
              maxLines: 4,
              keyboardType: TextInputType.multiline,
              textCapitalization: TextCapitalization.sentences,
              onChanged: (value) {
                setState(() {}); // Update character count
              },
            ),

            const SizedBox(height: 8),

            // Character count
            Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                Text(
                  '${_commandController.text.length} karakter',
                  style: TextStyle(
                    fontSize: 12,
                    color: _commandController.text.length > 1000 ? DS.danger : DS.textDim,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isLoading ? null : () => Navigator.of(context).pop(),
          child: const Text('Batal'),
        ),
        ElevatedButton.icon(
          onPressed: _isLoading || _commandController.text.trim().isEmpty
              ? null
              : _executeCommand,
          icon: _isLoading
              ? const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Icon(Icons.send),
          label: Text(_isLoading ? 'Memproses...' : 'Execute'),
          style: ElevatedButton.styleFrom(
            backgroundColor: DS.accent,
            foregroundColor: Colors.white,
          ),
        ),
      ],
    );
  }
}